CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE stockr_dev.books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    publisher VARCHAR(255),
    publish_date DATE,
    isbn VARCHAR(13) UNIQUE,
    price NUMERIC(10, 2),
    thumbnail_url TEXT,
    description TEXT,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_books_title ON stockr_dev.books(title);
CREATE INDEX idx_books_title_gin ON stockr_dev.books USING gin (title gin_trgm_ops);
CREATE INDEX idx_books_author ON stockr_dev.books(author);
CREATE INDEX idx_books_created_at_desc ON stockr_dev.books(created_at DESC);
