CREATE TABLE stockr_dev.rentals(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES stockr_dev.users(id) ON DELETE RESTRICT,
    book_id BIGINT NOT NULL REFERENCES stockr_dev.books(id) ON DELETE RESTRICT,
    rental_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    status_id INTEGER NOT NULL REFERENCES stockr_dev.rental_status(id) ON DELETE RESTRICT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rentals_user_id ON stockr_dev.rentals(user_id);
CREATE INDEX idx_rentals_book_id ON stockr_dev.rentals(book_id);
